// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFDLB2qpUpKIvO6ERfVWs_iaIa-FQkiVQ',
    appId: '1:519306226072:web:dfdfddab9b12e5fb19e3ed',
    messagingSenderId: '519306226072',
    projectId: 'my-gove',
    authDomain: 'my-gove.firebaseapp.com',
    storageBucket: 'my-gove.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOLwBsjmTMOga9Omwe4S20yl0_chnDads',
    appId: '1:519306226072:android:f5a6033310bfa18d19e3ed',
    messagingSenderId: '519306226072',
    projectId: 'my-gove',
    storageBucket: 'my-gove.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEy1PXgr1nRKURMb6Hdv0IJjkR9MyXrBg',
    appId: '1:519306226072:ios:a5772a665d4d1c5219e3ed',
    messagingSenderId: '519306226072',
    projectId: 'my-gove',
    storageBucket: 'my-gove.appspot.com',
    iosBundleId: 'com.example.myGovernateApp',
  );
}
